// Release-flow divergence fix — build-time version derivation.
//
// Runs as `prebuild`. Reads git state and writes `src/lib/generated/version.ts`
// exporting an APP_VERSION constant.
//
// Format rules (locked decision #6 in
// docs/superpowers/specs/2026-05-15-release-flow-divergence-fix-design.md):
//
//   1. At a tagged commit (e.g., prod build of vX.Y.Z):  "X.Y.Z"
//   2. On a release/vX.Y.Z branch (preview rc build):    "X.Y.Z-rc.<short-sha>"
//   3. Anywhere else with tags available:                "<latest-tag>-dev.<short-sha>"
//   4. No tags / shallow clone fallback:                 "0.0.0-dev.<short-sha>" (or "0.0.0-dev" if no sha)
//
// Note on case 3: we deliberately use the latest tag GLOBALLY
// (`git tag --list --sort=-v:refname`), not `git describe --tags --abbrev=0`
// which only reads tags reachable from HEAD. Reason: the v0.3.0 tag lives on
// main's merge commit (not an ancestor of qa), so describe-reachable would
// return a stale tag on qa. The global lookup is the right read for "what's
// the latest version we've shipped" regardless of branch divergence.
//
// See ADR 0009 Amendment 4 for full rationale.

import { execSync } from 'node:child_process'
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname } from 'node:path'

const OUTPUT = 'src/lib/generated/version.ts'

function git(args) {
  try {
    return execSync(`git ${args}`, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return ''
  }
}

function deriveVersion() {
  // Vercel's build container does a shallow clone WITHOUT tags by default,
  // which would force-feed every build into case 4 ("0.0.0-dev.<sha>")
  // instead of the more informative case 3 ("<latest-tag>-dev.<sha>").
  // Explicitly fetching tags here costs ~1s on Vercel and is a no-op on
  // a complete local clone. Failures (no origin, no network) are silent
  // — the wrapped git() returns empty on error, and we fall through to
  // case 4 as before.
  //
  // Note: --depth=1 was tried initially but seems to interact poorly with
  // --tags on Vercel's shallow clone; using a plain --tags fetch instead.
  git('fetch --tags origin')

  const shortSha =
    git('rev-parse --short HEAD') ||
    process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ||
    ''

  // Case 1: HEAD is at a tagged commit (e.g., prod build of a vX.Y.Z release).
  const exactTag = git('describe --tags --exact-match HEAD')
  if (exactTag) return exactTag.replace(/^v/, '')

  // Case 2: on a release/vX.Y.Z branch.
  const branch =
    process.env.VERCEL_GIT_COMMIT_REF ||
    git('symbolic-ref --short HEAD') ||
    ''
  const releaseBranchMatch = branch.match(/^release\/v(\d+\.\d+\.\d+)$/)
  if (releaseBranchMatch) {
    return `${releaseBranchMatch[1]}-rc.${shortSha || 'unknown'}`
  }

  // Case 3: dev build (qa / feature / chore / etc.). Use the latest tag in the
  // repo globally, not just what's reachable from HEAD.
  const allTags = git('tag --list --sort=-v:refname')
    .split('\n')
    .filter(Boolean)

  // Diagnostic — confirms whether case 3 has tags to work with. Visible
  // in Vercel build logs; harmless on local builds.
  console.log(
    `[derive-version] discovered ${allTags.length} tag(s)${
      allTags.length > 0 ? `; latest = ${allTags[0]}` : ''
    }`,
  )

  if (allTags.length > 0) {
    return `${allTags[0].replace(/^v/, '')}-dev.${shortSha || 'unknown'}`
  }

  // Case 4: no tags at all (fresh repo or shallow clone without tags).
  return shortSha ? `0.0.0-dev.${shortSha}` : '0.0.0-dev'
}

const version = deriveVersion()
const content = `// Generated by scripts/derive-version.mjs at build time. Do not edit.
export const APP_VERSION = ${JSON.stringify(version)}
`

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, content)
console.log(`[derive-version] APP_VERSION = ${version}`)
